### ISSUE TITLE
msix_fire_vector_notifier: Assertion `ret >= 0' failed

### ISSUE THREAD

**Issue by Wenzel** [IntelLabs/kafl.qemu#8]
Triggered with WIndows 10 guest and selffuzz test:

```ruby
Worker-00 Waiting for target to enter fuzz mode..
[+] Starting... C:\Users\vagrant\Desktop\selffuzz_test.exe
Worker-00 Waiting for target to enter fuzz mode..
[host_config] bitmap sizes = <0x10000,0x1000>
Worker-00 Waiting for target to enter fuzz mode..
[host_config] payload size = 128KB
Worker-00 Waiting for target to enter fuzz mode..
[host_config] worker id = 00
Worker-00 Waiting for target to enter fuzz mode..
[+] Allocating buffer for kAFL_payload struct
Worker-00 Waiting for target to enter fuzz mode..
[+] Submitting buffer address to hypervisor...
Worker-00 Waiting for target to enter fuzz mode..
[+] range buffer 350000...
Worker-00 Waiting for target to enter fuzz mode..
[+] Locking fuzzing ranges...
Worker-00 Waiting for target to enter fuzz mode..
[+] Range 0 enabled: 0  (0000000000000000-0000000000000000)
Worker-00 Waiting for target to enter fuzz mode..
[+] Range 1 enabled: 0  (0000000000000000-0000000000000000)
Worker-00 Waiting for target to enter fuzz mode..
[+] Range 2 enabled: 0  (0000000000000000-0000000000000000)
Worker-00 Waiting for target to enter fuzz mode..
[+] Range 3 enabled: 0  (0000000000000000-0000000000000000)
Worker-00 Waiting for target to enter fuzz mode..
[+] Range: 0x0000000000401A3F-0x0000000000401B73
qemu-system-x86_64: hw/pci/msix.c:113: msix_fire_vector_notifier: Assertion `ret >= 0' failed.
Worker-00 Waiting for target to enter fuzz mode..
Worker-00 Guest ABORT: Exit after SIGABRT. Check logs for details.
Worker-00 Failed to connect to Qemu: Guest ABORT: Exit after SIGABRT. Check logs for details.
```

Assertion: https://github.com/IntelLabs/kafl.qemu/blob/7bb7b75bf59e49101d04a9dade1ab2edd5d4c4bd/hw/pci/msix.c#L113

**Comment by Wenzel** [comment]
This happened after I switched my Windows VM build to virtio for better performance.

**Comment by Wenzel** [comment]
Managed to get a backtrace !

```c
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737306179136) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737306179136) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737306179136, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7842476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff78287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff782871b in __assert_fail_base (fmt=0x7ffff79dd150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555556118ae5 "ret >= 0", file=0x5555561ad380 "hw/pci/msix.c", line=113,
    function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff7839e96 in __GI___assert_fail (assertion=assertion@entry=0x555556118ae5 "ret >= 0", file=file@entry=0x5555561ad380 "hw/pci/msix.c", line=line@entry=113,
    function=function@entry=0x5555561ad550 <__PRETTY_FUNCTION__.3> "msix_fire_vector_notifier") at ./assert/assert.c:101
#7  0x0000555555dc0201 in msix_fire_vector_notifier (is_masked=false, vector=1, dev=0x5555578b3cd0) at hw/pci/msix.c:113
#8  msix_handle_mask_update (was_masked=true, vector=1, dev=0x5555578b3cd0) at hw/pci/msix.c:125
#9  msix_load (dev=dev@entry=0x5555578b3cd0, f=f@entry=0x7fffec150a20) at hw/pci/msix.c:459
#10 0x0000555555e4040b in virtio_pci_load_config (d=0x5555578b3cd0, f=0x7fffec150a20) at hw/virtio/virtio-pci.c:182
#11 0x0000555555b96bfa in virtio_load (vdev=0x5555578bbe40, f=0x7fffec150a20, version_id=2) at /home/mtarral/kafl/kafl/qemu/hw/virtio/virtio.c:2902
#12 0x0000555555bf50d6 in get_handler (vmsd_name=0x555556111a42 "virtio-blk", field=0x5555568b2fc0 <__compound_literal.0>, size=0, curr_elem=0x5555578bbe40, f=0x7fffec150a20, self=0x7fffec27f570)
    at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/state_reallocation.c:440
#13 fdl_vmstate_load_state (self=0x7fffec27f570, f=0x7fffec150a20, vmsd=0x5555565a4360 <vmstate_virtio_blk>, opaque=0x5555578bbe40, version_id=2, opaque_ptr=<optimized out>)
    at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/state_reallocation.c:681
#14 0x0000555555bf5e2a in fdl_vmstate_load (version_id=2, se=0x5555579da460, f=0x7fffec150a20, self=0x7fffec27f570) at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/state_reallocation.c:732
#15 fdl_enumerate_section (mis=<optimized out>, f=0x7fffec150a20, self=0x7fffec27f570) at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/state_reallocation.c:817
#16 fdl_enumerate_global_states (f=0x7fffec150a20, self=0x7fffec27f570) at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/state_reallocation.c:857
#17 state_reallocation_new (f=f@entry=0x7fffec150a20) at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/state_reallocation.c:902
#18 0x0000555555bf44dd in nyx_device_state_init () at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/nyx_device_state.c:423
#19 0x0000555555be7a7e in fast_snapshot_init_operation (pre_snapshot=false, snapshot_folder=0x0, self=0x555556a4c8a0) at /home/mtarral/kafl/kafl/qemu/nyx/fast_vm_reload.c:82
#20 fast_reload_create_in_memory (self=0x555556a4c8a0) at /home/mtarral/kafl/kafl/qemu/nyx/fast_vm_reload.c:412
#21 0x0000555555be819d in create_root_snapshot () at /home/mtarral/kafl/kafl/qemu/nyx/fast_vm_reload_sync.c:131
#22 create_root_snapshot () at /home/mtarral/kafl/kafl/qemu/nyx/fast_vm_reload_sync.c:121
#23 perform_task_no_block_mode (self=<optimized out>, request=REQUEST_SAVE_SNAPSHOT_ROOT_FIX_RIP) at /home/mtarral/kafl/kafl/qemu/nyx/fast_vm_reload_sync.c:194
#24 request_fast_vm_reload (self=<optimized out>, request=request@entry=REQUEST_SAVE_SNAPSHOT_ROOT_FIX_RIP) at /home/mtarral/kafl/kafl/qemu/nyx/fast_vm_reload_sync.c:269
#25 0x0000555555bfc6b4 in handle_hypercall_kafl_next_payload (run=<optimized out>, hypercall_arg=<optimized out>, cpu=0x555556bd4180) at /home/mtarral/kafl/kafl/qemu/nyx/hypercall/hypercall.c:113
#26 handle_hypercall_kafl_next_payload (run=<optimized out>, cpu=0x555556bd4180, hypercall_arg=<optimized out>) at /home/mtarral/kafl/kafl/qemu/nyx/hypercall/hypercall.c:94
#27 0x0000555555bfd540 in handle_kafl_hypercall (run=run@entry=0x7ffff7fbe000, cpu=cpu@entry=0x555556bd4180, hypercall=hypercall@entry=112, arg=0) at /home/mtarral/kafl/kafl/qemu/nyx/hypercall/hypercall.c:888
#28 0x0000555555b281b8 in kvm_cpu_exec (cpu=cpu@entry=0x555556bd4180) at /home/mtarral/kafl/kafl/qemu/accel/kvm/kvm-all.c:2676
#29 0x0000555555aff4e4 in qemu_kvm_cpu_thread_fn (arg=0x555556bd4180) at /home/mtarral/kafl/kafl/qemu/cpus.c:1318
#30 qemu_kvm_cpu_thread_fn (arg=arg@entry=0x555556bd4180) at /home/mtarral/kafl/kafl/qemu/cpus.c:1290
#31 0x0000555555ffbadb in qemu_thread_start (args=<optimized out>) at util/qemu-thread-posix.c:519
#32 0x00007ffff7894b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#33 0x00007ffff7926a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

bt -full
```c
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737306179136) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7ffff5243640
        old_mask = {__val = {140737155244980, 140737155244880, 140737155244980, 0, 0, 0, 0, 0, 553868600016, 21292655360, 140737159036928, 0, 140737159037792, 4091562995065211648, 18446744073709551615, 
            140737347954336}}
        ret = <optimized out>
        pd = <optimized out>
        old_mask = <optimized out>
        ret = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        __private = <optimized out>
        __oldval = <optimized out>
        result = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=140737306179136) at ./nptl/pthread_kill.c:78
No locals.
#2  __GI___pthread_kill (threadid=140737306179136, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
No locals.
#3  0x00007ffff7842476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007ffff78287f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7fffec252350, sa_sigaction = 0x7fffec252350}, sa_mask = {__val = {0, 140737155244880, 2147483647, 4, 140737347683594, 0, 72818196608, 140737306174320, 
              4091562995065211648, 0, 18446744073709550504, 16, 93825005179776, 113, 93825004571365, 93825009346464}}, sa_flags = -141929261, sa_restorer = 0x7ffff7a16600 <_IO_file_jumps>}
        sigs = {__val = {32, 140737347954336, 93825005179776, 113, 93825004571365, 93825009346464, 140737306179136, 140737346267502, 206158430256, 140737306174544, 206158430232, 140737306174544, 
            140737306174336, 4091562995065211648, 140737488346900, 140737347684034}}
#5  0x00007ffff782871b in __assert_fail_base (fmt=0x7ffff79dd150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555556118ae5 "ret >= 0", file=0x5555561ad380 "hw/pci/msix.c", line=113, 
    function=<optimized out>) at ./assert/assert.c:92
        str = 0x7fffec252350 "RV\211\023\370\177"
        total = 4096
#6  0x00007ffff7839e96 in __GI___assert_fail (assertion=assertion@entry=0x555556118ae5 "ret >= 0", file=file@entry=0x5555561ad380 "hw/pci/msix.c", line=line@entry=113, 
    function=function@entry=0x5555561ad550 <__PRETTY_FUNCTION__.3> "msix_fire_vector_notifier") at ./assert/assert.c:101
No locals.
#7  0x0000555555dc0201 in msix_fire_vector_notifier (is_masked=false, vector=1, dev=0x5555578b3cd0) at hw/pci/msix.c:113
        msg = <optimized out>
        ret = <optimized out>
        msg = <optimized out>
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "msix_fire_vector_notifier"
#8  msix_handle_mask_update (was_masked=true, vector=1, dev=0x5555578b3cd0) at hw/pci/msix.c:125
        is_masked = <optimized out>
        is_masked = <optimized out>
#9  msix_load (dev=dev@entry=0x5555578b3cd0, f=f@entry=0x7fffec150a20) at hw/pci/msix.c:459
        n = 2
        vector = 1
#10 0x0000555555e4040b in virtio_pci_load_config (d=0x5555578b3cd0, f=0x7fffec150a20) at hw/virtio/virtio-pci.c:182
        proxy = 0x5555578b3cd0
        vdev = 0x5555578bbe40
        ret = 0
#11 0x0000555555b96bfa in virtio_load (vdev=0x5555578bbe40, f=0x7fffec150a20, version_id=2) at /home/mtarral/kafl/kafl/qemu/hw/virtio/virtio.c:2902
        i = <optimized out>
        ret = <optimized out>
        config_len = <optimized out>
        num = <optimized out>
        features = <optimized out>
        qbus = 0x5555578bbdc8
        __func__ = "virtio_load"
        k = 0x555556aae5d0
        vdc = 0x555556b69030
        _rcu_read_auto = <optimized out>
#12 0x0000555555bf50d6 in get_handler (vmsd_name=0x555556111a42 "virtio-blk", field=0x5555568b2fc0 <__compound_literal.0>, size=0, curr_elem=0x5555578bbe40, f=0x7fffec150a20, self=0x7fffec27f570)
    at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/state_reallocation.c:440
        ret = <optimized out>
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "get_handler"
        __func__ = "get_handler"
#13 fdl_vmstate_load_state (self=0x7fffec27f570, f=0x7fffec150a20, vmsd=0x5555565a4360 <vmstate_virtio_blk>, opaque=0x5555578bbe40, version_id=2, opaque_ptr=<optimized out>)
    at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/state_reallocation.c:681
        tmp_opaque_ptr = <optimized out>
        curr_elem = 0x5555578bbe40
        first_elem = 0x5555578bbe40
        i = 0
        n_elems = 1
        size = 0
        field = 0x5555568b2fc0 <__compound_literal.0>
        ret = <optimized out>
        total_size = <optimized out>
        __PRETTY_FUNCTION__ = "fdl_vmstate_load_state"
#14 0x0000555555bf5e2a in fdl_vmstate_load (version_id=2, se=0x5555579da460, f=0x7fffec150a20, self=0x7fffec27f570) at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/state_reallocation.c:732
        t = 0x5555579da598
#15 fdl_enumerate_section (mis=<optimized out>, f=0x7fffec150a20, self=0x7fffec27f570) at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/state_reallocation.c:817
        instance_id = 0
        version_id = 2
        section_id = 41
        se = 0x5555579da460
        idstr = "0000:00:03.0/virtio-blk\000\220\000\000\354\377\177\000\000\a\000\000\000\000\000\000\000\213\260\376UUU\000\000\061\060\060\000v\000\000\000P\204\000\000\000\000\000\000\000m'\354\377\177\000\000\244/Ї8\000\000[T\b\000\000\000\000\000\000\200\204\000\000\000\000\000\000\021\002\000\000\000\000\000\000F\b\000\000A\002\000\000B\000\000\000\000\000\000\000\b\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000|\000\000\000x\000\000\000v\000\000\000\235\000\000\000\221\247\002\000\000\000\000\000\000\200\000\000\000\000\000\000\360;\217\354\377\177\000\000\020\204\003\000\000\000\000\000P\204\000\000\000\000\000\000\060\000\000\354\377\177\000\000\000\000\000\000\000\000\000\000"...
        ret = <optimized out>
#16 fdl_enumerate_global_states (f=0x7fffec150a20, self=0x7fffec27f570) at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/state_reallocation.c:857
        section_type = <optimized out>
        mis = <optimized out>
        section_type = <optimized out>
        mis = <optimized out>
#17 state_reallocation_new (f=f@entry=0x7fffec150a20) at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/state_reallocation.c:902
        self = 0x7fffec27f570
        __PRETTY_FUNCTION__ = "state_reallocation_new"
#18 0x0000555555bf44dd in nyx_device_state_init () at /home/mtarral/kafl/kafl/qemu/nyx/snapshot/devices/nyx_device_state.c:423
        self = 0x7fffec275960
        local_err = <optimized out>
        fast_savevm_opaque = {f = 0x0, buf = 0x7ffc982ff010 "QEVM", buflen = 140737159037728, pos = 170719, output_buffer = 0x7ffc99300010, output_buffer_size = 0x7fffec275988}
        fast_loadvm_opaque = {f = 0x0, buf = 0x7ffc982ff010 "QEVM", buflen = 93825021725936, pos = 0, output_buffer = 0x0, output_buffer_size = 0xfd000000}
        tmp_buf = 0x7ffc982ff010
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "nyx_device_state_init"
        f = 0x7fffec8076c0
        file_dump = 0x7fffec150a20
#19 0x0000555555be7a7e in fast_snapshot_init_operation (pre_snapshot=false, snapshot_folder=0x0, self=0x555556a4c8a0) at /home/mtarral/kafl/kafl/qemu/nyx/fast_vm_reload.c:82
        __PRETTY_FUNCTION__ = "fast_snapshot_init_operation"
#20 fast_reload_create_in_memory (self=0x555556a4c8a0) at /home/mtarral/kafl/kafl/qemu/nyx/fast_vm_reload.c:412
        __PRETTY_FUNCTION__ = "fast_reload_create_in_memory"
#21 0x0000555555be819d in create_root_snapshot () at /home/mtarral/kafl/kafl/qemu/nyx/fast_vm_reload_sync.c:131
No locals.
#22 create_root_snapshot () at /home/mtarral/kafl/kafl/qemu/nyx/fast_vm_reload_sync.c:121
No locals.
#23 perform_task_no_block_mode (self=<optimized out>, request=REQUEST_SAVE_SNAPSHOT_ROOT_FIX_RIP) at /home/mtarral/kafl/kafl/qemu/nyx/fast_vm_reload_sync.c:194
        cpu = 0x555556bd4180
        x86_cpu = 0x555556bd4180
        env = 0x555556bdc9f0
        cpu = <optimized out>
        x86_cpu = <optimized out>
        __func__ = "perform_task_no_block_mode"
        env = <optimized out>
#24 request_fast_vm_reload (self=<optimized out>, request=request@entry=REQUEST_SAVE_SNAPSHOT_ROOT_FIX_RIP) at /home/mtarral/kafl/kafl/qemu/nyx/fast_vm_reload_sync.c:269
        cpu = <optimized out>
        __PRETTY_FUNCTION__ = "request_fast_vm_reload"
#25 0x0000555555bfc6b4 in handle_hypercall_kafl_next_payload (run=<optimized out>, hypercall_arg=<optimized out>, cpu=0x555556bd4180) at /home/mtarral/kafl/kafl/qemu/nyx/hypercall/hypercall.c:113
No locals.
#26 handle_hypercall_kafl_next_payload (run=<optimized out>, cpu=0x555556bd4180, hypercall_arg=<optimized out>) at /home/mtarral/kafl/kafl/qemu/nyx/hypercall/hypercall.c:94
        i = <optimized out>
#27 0x0000555555bfd540 in handle_kafl_hypercall (run=run@entry=0x7ffff7fbe000, cpu=cpu@entry=0x555556bd4180, hypercall=hypercall@entry=112, arg=0) at /home/mtarral/kafl/kafl/qemu/nyx/hypercall/hypercall.c:888
        ret = -1
#28 0x0000555555b281b8 in kvm_cpu_exec (cpu=cpu@entry=0x555556bd4180) at /home/mtarral/kafl/kafl/qemu/accel/kvm/kvm-all.c:2676
        attrs = <optimized out>
        run = <optimized out>
        ret = <optimized out>
        run_ret = <optimized out>
        timeout_reload_pending = false
        __PRETTY_FUNCTION__ = "kvm_cpu_exec"
        __func__ = "kvm_cpu_exec"
#29 0x0000555555aff4e4 in qemu_kvm_cpu_thread_fn (arg=0x555556bd4180) at /home/mtarral/kafl/kafl/qemu/cpus.c:1318
        cpu = <optimized out>
        r = <optimized out>
        cpu = <optimized out>
        r = <optimized out>
#30 qemu_kvm_cpu_thread_fn (arg=arg@entry=0x555556bd4180) at /home/mtarral/kafl/kafl/qemu/cpus.c:1290
        cpu = 0x555556bd4180
        r = <optimized out>
#31 0x0000555555ffbadb in qemu_thread_start (args=<optimized out>) at util/qemu-thread-posix.c:519
        __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {140737306179136, 1588045853385027960, 140737306179136, 7, 140737346357328, 140737488343712, 4853922165259235704, 1588039808942993784}, 
              __mask_was_saved = 0}}, __pad = {0x7ffff5242ab0, 0x0, 0x0, 0x0}}
        __cancel_routine = 0x555555ffbb30 <qemu_thread_atexit_notify>
        __cancel_arg = <optimized out>
        __not_first_call = <optimized out>
        qemu_thread_args = <optimized out>
        start_routine = 0x555555aff3d0 <qemu_kvm_cpu_thread_fn>
        arg = 0x555556bd4180
        r = <optimized out>
#32 0x00007ffff7894b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737488343360, -4853910398592880264, 140737306179136, 7, 140737346357328, 140737488343712, 4853922165282304376, 4853927290214150520}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#33 0x00007ffff7926a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.
```

Context:
![image](https://github.com/IntelLabs/kafl.qemu/assets/964610/c2a6df8c-7e1c-4c4d-8d85-cee8bd157177)


The function responsible for returning the bad `ret` value:
[`virtio_pci_vector_unmask`](https://github.com/IntelLabs/kafl.qemu/blob/kafl_stable/hw/virtio/virtio-pci.c#L843)
```c
(gdb) p dev->msix_vector_use_notifier
$3 = (MSIVectorUseNotifier) 0x555555e41b80 <virtio_pci_vector_unmask>
```

**Comment by Wenzel** [comment]
I've deactivated the assert, and it works so far for both harnesses (userspace, driver).

Thanks for the comments @il-steffen, they will be useful if we need to have a deeper look at this.
But maybe upgrading to QEMU 5.0 or 6.0 will fix that issue in the future also.

Closing this for now.

**Comment by il-steffen** [comment]
> I've deactivated the assert, and it works so far for both harnesses (userspace, driver).

🤡

**Comment by schumilo** [comment]
Yes, so from my side, this code and the "virtio" type have never been tested with the snapshot mechanism. Possibly the virtio restore code needs to be rewritten from scratch to make everything work well (most likely simply lifting to a more recent QEMU version won't fix this issue) but until then, it might work, but it also might cause other issues...
